config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :agent do
    resources :rappers, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:index] do
      member do
        patch :accept
        patch :refuse
      end
    end
    # patch "bookings/:id/accept", to: "bookings#accept"
    # patch "bookings/:id/refuse", to: "bookings#refuse"
  end

  resources :rappers, only: [:index, :show] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :rapper
end

app/models/rapper.rb
class Rapper < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :agent, class_name: "User"
  has_many :bookings, dependent: :destroy
  mount_uploader :picture, PhotoUploader
  mount_uploader :background_picture, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rappers, foreign_key: :agent_id
  has_many :bookings
  mount_uploader :picture, PhotoUploader
end

app/controllers/agent/bookings_controller.rb
class Agent::BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :refuse]

  def index
    @all_bookings = Booking.all
    @id = current_user.id
    @bookings = []
    @all_bookings.each do |booking|
      if booking.rapper.agent.id == current_user.id
        @bookings << booking
      end
    end

    @past = []
    @accepted = []
    @pending = []

    @bookings.each do |booking|
      if booking.ending_on < Date.current
        @past << booking
      elsif booking.status == "pending"
        @pending << booking
      else booking.status == "accepted"
        @accepted << booking
      end
    end
  end

  def accept
    @booking.status = "accepted"
    @booking.save
    redirect_to agent_bookings_path
  end

  def refuse
    @booking.status = "refused"
    @booking.save
    redirect_to agent_bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:status)
  end
end

app/controllers/agent/rappers_controller.rb
class Agent::RappersController < ApplicationController
  before_action :set_rapper, only: [:edit, :update, :destroy]

  def index
    @rappers = current_user.rappers
  end

  def new
    @rapper = Rapper.new
  end

  def create
    @rapper = Rapper.new(rapper_params)
    @rapper.agent = User.find(current_user.id)
    if @rapper.save
      redirect_to agent_rappers_path(@rapper)
    else
      render :new
    end
  end

  def edit
    # @rapper = Rapper.find(params[:id])
  end

  def update
    # @rapper = Rapper.find(params[:id])
    @agent = User.find(current_user.id)
    @rapper.update(rapper_params)
    redirect_to agent_rappers_path(@rapper), :notice => "Your changes have been saved"
  end

  def destroy
    # @rapper = Rapper.find(params[:id])
    @rapper.destroy
    redirect_to agent_rappers_path, :notice => "Your rapper has been deleted"
  end

  private

  def set_rapper
    @rapper = Rapper.find(params[:id])
  end

  def rapper_params
    params.require(:rapper).permit(:blaz, :description, :punchline, :style, :origin, :price_per_day, :picture)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  def index
    bookings = Booking.all
    @past = []
    @accepted = []
    @pending = []

    bookings.each do |booking|
      if booking.ending_on < Date.current
        @past << booking
      elsif booking.status == "pending"
        @pending << booking
      else booking.status == "accepted"
        @accepted << booking
      end
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @rapper = Rapper.find(params[:rapper_id])
    @booking.user_id = current_user.id
    @booking.rapper_id = @rapper.id
    @booking.status = "pending"
    @booking.total_price = @rapper.price_per_day * (@booking.ending_on - @booking.starting_on)


    if @booking.save
      redirect_to bookings_path
    else
      render 'rappers/show'
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:starting_on, :ending_on)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rappers_controller.rb
class RappersController < ApplicationController
  def index
    if params[:query].present?
      @rappers = Rapper.where("blaz ILIKE ?", "%#{params[:query]}%").where.not(latitude: nil, longitude: nil)
      @markers = marker(@rappers)
    else
      @rappers = Rapper.all.where.not(latitude: nil, longitude: nil)
      @markers = marker(@rappers)
    end
  end

  def show
    @rapper = Rapper.find(params[:id])
    @booking = Booking.new
  end

  private

  def marker(rappers)

    icon = {
      url: "http://www.myiconfinder.com/uploads/iconsets/256-256-87d8abae0d940c0a7145c55cf1c2e3dd-dollar.png"
    }

    @markers = rappers.map do |rapper|
      {
        lat: rapper.latitude,
        lng: rapper.longitude,
        infoWindow: { content: render_to_string(partial: "/rappers/map_box", locals: { rapper: rapper }) },
        icon: "http://res.cloudinary.com/djntzkorq/image/upload/v1534516977/dollar-sign-solid.png",
        title: rapper.blaz
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agent/bookings/index.html.erb
<div class="form-container">
  <h2 class='text-center'> All your shows </h2>
  <div class="booking-index">
    <div class="container">
      <%  if @pending[0].nil? %>
      <h4>No new bookings yet (don't worry it will come)</h4>
      <% else %>
        <h4>You have new bookings ! </h4>
        <div class="row">
        <p><% @pending.each do |pending| %></p>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
            url('<%= pending.rapper.picture %>');">
              <div class="card-category"><%= pending.status %></div>
              <div class="card-description-booking">
                <h4><%= pending.rapper.blaz %></h4>
                <p><%= pending.total_price %>$</p>
                <p>From <%= pending.starting_on %> to <%= pending.ending_on %></p>
              </div>
            </div>
            <%= link_to accept_agent_booking_path(pending.id), method: :patch do %>
               <i class="btn btn-primary"> Accept </i>
            <% end %>
            <%= link_to refuse_agent_booking_path(pending.id), method: :patch do %>
              <i class="btn btn-danger"> Refuse </i>
            <% end %>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <br>
    <div class="container">
      <% if @accepted[0] != nil  %>
        <h4>Next perfomances </h4>
        <div class="row">
        <p><% @accepted.each do |accepted| %></p>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= accepted.rapper.picture %>');">
              <div class="card-category"><%= accepted.status %></div>
              <div class="card-description-booking">
                <h4><%= accepted.rapper.blaz %></h4>
                <p><%= accepted.total_price %>$</p>
                <p>From <%= accepted.starting_on %> to <%= accepted.ending_on %></p>
              </div>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <br>

    <div class="container">
      <% if @past != nil  %>
        <h4>Past shows of your rappers</h4>
        <div class="row">
        <p><% @past.each do |past| %></p>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= past.rapper.picture %>');">
              <div class="card-category"><%= past.status %></div>
              <div class="card-description-booking">
                <h4><%= past.rapper.blaz %></h4>
                <p><%= past.total_price %>$</p>
                <p>From <%= past.starting_on %> to <%= past.ending_on %></p>
              </div>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/agent/rappers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <h1>Wanna change something?</h1>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= simple_form_for [@agent, @rapper], url: agent_rapper_path(@rapper), method: :patch do |f| %>
        <%= f.input :blaz %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :description %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :punchline %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :style %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :origin %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :price_per_day %>
    </div>
  </div>
   <div class="row">
      <div class="form-group col-sm-offset-4 col-sm-4">
        <%= f.input :picture %>
      </div>
  </div>
   <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :picture_cache, as: :hidden %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
       <%= f.submit "Save modifications", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/agent/rappers/index.html.erb
<div class="form-container">
<h2 class='text-center'> All your rappers </h2>
<div class="index-container">
    <div class="rappers-container">
      <div class="row">
      <% @rappers.each do |rapper| %>
        <div class="col-md-4">
          <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
          url('<%= cl_image_path rapper.picture %>')">
            <div class="btn-update-delete">
              <div><%= link_to "+", agent_rapper_path(rapper), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %></div>
              <div><%= link_to "!", edit_agent_rapper_path(rapper), class: "card-remove-link"  %></div>
            </div>
            <%= link_to "", rapper_path(rapper), class: "card-link" %>
            <div class="card-category"><%= rapper.style %></div>
            <div class="card-description-booking">
              <h4><%= rapper.blaz %></h4>
              <p><%= rapper.price_per_day %>$/day</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-offset-5 col-md-4">
          <%= link_to "Add a rapper", new_agent_rapper_path, class: "btn btn-primary text-center" %>
        </div>
      </div>
    </div>
</div>

app/views/agent/rappers/new.html.erb
<div class="container">
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <h1>Add a new rapper</h1>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= simple_form_for [@rapper], url: agent_rappers_path(@rapper), method: :post do |f| %>
        <%= f.input :blaz %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :description %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :punchline %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :style %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :origin %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :price_per_day %>
    </div>
  </div>
   <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :picture %>
    </div>
  </div>
   <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
      <%= f.input :picture_cache, as: :hidden %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-offset-4 col-sm-4">
       <%= f.submit "Add a rapper", class: "btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="form-container">
  <h2 class='text-center'> All your bookings </h2>
  <div class="booking-index">
    <div class="container">
      <% if @accepted.empty? %>
          <h4 class='text-center'> No rapper booked ? Go all rappers we have</h4>
          <br>
          <br>
          <div class="row">
            <div class="col-md-6 col-md-offset-5">
              <%= link_to "Book a rapper", rappers_path, class: 'btn btn-primary' %>
            </div>
        </div>
      <% else %>
        <h4>Next rapper at my party !! </h4>
        <div class="row">
        <p><% @accepted.each do |accepted| %></p>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= accepted.rapper.picture %>');">
              <div class="card-category"><%= accepted.status %></div>
              <div class="card-description-booking">
                <h4><%= accepted.rapper.blaz %></h4>
                <p><%= accepted.total_price %>$</p>
                <p>From <%= accepted.starting_on %> to <%= accepted.ending_on %></p>
              </div>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <% end %>
        </div>
      <% end  %>
    </div>
    <br>
    <br>

    <div class="container">
      <% if @pending.empty?  %>
        <% 1+1 %>
      <% else %>
        <h4>They'll maybe come to my house !</h4>
        <div class="row">
        <p><% @pending.each do |pending| %></p>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= pending.rapper.picture %>');">
              <div class="card-category"><%= pending.status %></div>
              <div class="card-description-booking">
                <h4><%= pending.rapper.blaz %></h4>
                <p><%= pending.total_price %>$</p>
                <p>From <%= pending.starting_on %> to <%= pending.ending_on %></p>
              </div>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <br>

    <div class="container">
      <% if @pending.empty?  %>
        <% 1+1 %>
      <% else %>
        <h4>My fucking last special guest !</h4>
        <div class="row">
        <p><% @past.each do |past| %></p>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= past.rapper.picture %>');">
              <div class="card-category"><%= past.status %></div>
              <div class="card-description-booking">
                <h4><%= past.rapper.blaz %></h4>
                <p><%= past.total_price %>$</p>
                <p>From <%= past.starting_on %> to <%= past.ending_on %></p>
              </div>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Air'nB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hompage">
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://thebackpackerz.com/wp-content/uploads/2015/10/JessicaLehrman_Artwork_HipHop-4.jpg');">
    <div class="banner-content">
      <h1>
        <span id="banner-typed-text"></span>
      </h1>
      <br><br><br>
      <%= link_to "Book a rapper", rappers_path, class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
  <div class="banner-2">
    <h2>Top rappers available !</h2>
    <div class="banner-cards">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://res.cloudinary.com/djntzkorq/image/upload/v1534330074/j4hqsofuds5if9nieobf.jpg');">
                <div class="card-description">
                  <h3>Booba</h3>
                  <p>AKA Le Duc de Boulogne</p>
                </div>
                <a class="card-link" href="#" ></a>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/djntzkorq/image/upload/v1534330115/zoc500hwnlhm8joctru8.jpg');">
              <div class="card-description">
                <h3>Notorious B.I.G</h3>
                <p>AKA Biggie Smalls</p>
              </div>
              <a class="card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card-home">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/djntzkorq/image/upload/v1534251725/sojikie8afpb9ebeko3j.jpg');">
                <div class="card-description">
                  <h3>SCH</h3>
                  <p>AKA Le French Lisseur</p>
                </div>
                <a class="card-link" href="#" ></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br> <br>
      <%= link_to "Book a rapper", rappers_path, class: 'btn btn-primary btn-lg' %>
      <br> <br> <br> <br>
    </div>
  </div>
</div>

app/views/rappers/_creation_form.html.erb
<%= simple_form_for @booking, url: rapper_bookings_path(@rapper) do |f| %>
  <%= f.input :starting_on, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :ending_on, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.button :submit, "Go", class: "btn btn-primary" %>
<% end %>

app/views/rappers/_map_box.html.erb
<div class="map-box">
  <h5><%= rapper.blaz %></h5>
    <h6><em><%= rapper.punchline %></em></h6>
</div>

app/views/rappers/index.html.erb
<h1 class="text-center">All ours rappers</h1>

<div class="index-container">
  <div class="main-container">
    <div class="container">
      <div class="form">
        <%= form_tag rappers_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a rapper" %>
        <% end %>
      </div>
      <div class="row">
        <% @rappers.each do |rapper| %>
          <div class="col-md-4">
            <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
            url('<%= cl_image_path rapper.picture %>')">
              <%= link_to "", rapper_path(rapper), class: "card-link" %>
              <div class="card-category"><%= rapper.style %></div>
              <div class="card-description-booking">
                <h4><%= rapper.blaz %></h4>
                <p><%= rapper.price_per_day %>$/day</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="map" data-markers="<%= @markers.to_json %>"></div>
  </div>
</div>

app/views/rappers/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,20,40,0.1) 50%), url('<%= cl_image_path @rapper.background_picture %>')">
    <div class="banner-blaz"><%= @rapper.blaz %>
    </div>
    <div class="banner-price"><%= @rapper.price_per_day %> $
    </div>
    <div class="banner-details">
      <p>Description : <%= @rapper.description %></p>
      <br>
      <p>Punchline : <%= @rapper.punchline %></p>
      <br>
      <p>Style : <%= @rapper.style %></p>
      <br>
      <p>Origin : <%= @rapper.origin %></p>
    </div>
</div>
<br>
<br>
<br>
<div class="center-container">
  <div>
    <iframe width="700" height="393,75" src='https://youtube.com/embed/<%= @rapper.video %>' frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
</div>


<div class="header-show">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Book <%= @rapper.blaz %></h2>
    <%= simple_form_for @booking, url: rapper_bookings_path(@rapper) do |f| %>
      <%= f.input :starting_on, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :ending_on, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Go", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>


rails generate migration AddVideoToRappers video:string

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/rappers" class="navbar-wagon-brand">
    <%= image_tag "logo.svg" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add a rapper", new_agent_rapper_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Rappers", agent_rappers_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Shows", agent_bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Profile", edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag cl_image_path("samples/animals/cat.jpg"), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
           <!--  <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>